### ISSUE TITLE
Readthedocs Access

### ISSUE THREAD

**Issue by directionless** [osquery/foundation#11]
How is readthedocs managed. @zwass you said you maybe talked to @theopolis about it?

**Comment by mike-myers-tob** [comment]
When we made the `osql` fork of osquery, we set up a readthedocs.io account for it.

Someone (@theopolis ?) has a ReadTheDocs account and points it at the osquery repo on GitHub. This person could add the rest of the technical committee here as maintainers.

To merely update the docs, though, it should just require changing the docs, which are in Markdown here: https://github.com/osquery/osquery/tree/master/docs

The project settings and sidebar for ReadTheDocs is kept in the root as mkdocs.yml.

**Comment by zwass** [comment]
I spoke to @theopolis who is adding the TAB folks as maintainers on ReadTheDocs.

**Comment by theopolis** [comment]
Right, to reiterate, anyone can update the documentation content through a PR to osquery.

**Comment by directionless** [comment]
@theopolis Added several more members of the TSC
