### ISSUE TITLE
Proposal: Change the github billing plan

### ISSUE THREAD

**Issue by directionless** [osquery/foundation#19]
I noticed that we're on a legacy GitHub Bronze billing plan, currently covered by FaceBook. 

My read on the current plans, is that this primarily gets us private repos, which we don't have. It might also enable some things around team discussions. It probably does not include beta features like [Triage](https://github.blog/changelog/2019-05-23-triage-and-maintain-roles-beta/)

I propose we confirm with support that moving to [Team for open source](https://help.github.com/en/articles/types-of-github-accounts#organization-accounts) isn't going to lose us anything, and then work with github to convert us.

As this is a billing change, I want to poll the TSC folks, @theopolis in particular, for his Facebook background.

**Comment by caniszczyk** [comment]
GitHub has a nonprofit plan you should apply for: https://github.com/nonprofit

If there are no billing needs then you should just move to the default plan.

**Comment by directionless** [comment]
I reached out to github, to try to understand the differences between the nonprofit plan and the open source plan.

**Comment by directionless** [comment]
Both @theopolis and I reached out to github about this. I don't think either has heard anything. Still ongoing.

**Comment by theopolis** [comment]
Correct, I have not heard anything yet.

**Comment by directionless** [comment]
GitHub did get back to me, with a very brief note about needing to talk to sales. I've pinged them on that thread.

**Comment by directionless** [comment]
I have our business info from LF. We are a 501-c6. I've communicated information to githuib

**Comment by caniszczyk** [comment]
@directionless I'm talking to GitHub, we need to move our plan off of the enterprise plan to a normal open source plan for them to make the changes. Can you do this as I don't have admin access to the github org

**Comment by directionless** [comment]
This went on forever. Sorry y'all.

Github comped us a Teams account. Which I think does everything we need. Thanks github!
