### ISSUE TITLE
Slack Onboarding Heroku App

### ISSUE THREAD

**Issue by directionless** [osquery/foundation#23]
We run https://osquery-slack.herokuapp.com/ for slack onboarding. Anyone have access to that? @theopolis 

Relates to: #4

**Comment by theopolis** [comment]
I have access to this, yes. I'm surprised we still need this (why doesn't Slack support this workflow natively??). 

I am happy to move it somewhere else, perhaps to EC2 if we get an AWS account setup.

**Comment by directionless** [comment]
A quick google search says slack still doesn't really do this. We can get an invite URL, and publish it. But, those expire monthly. Otherwise we run a webapp.

**Comment by theopolis** [comment]
We moved to using a Slack invite code: https://github.com/osquery/osquery/pull/6617
