### ISSUE TITLE
Provide CLA to people *before* they sign it

### ISSUE THREAD

**Issue by directionless** [osquery/foundation#38]
At least a couple of times, I've been pinged by users for the CLA _before_ they sign it. At least right now, I can't figure out how to do that in EasyCLA. (this is a tracking issue)

One issue seems to be that the admin interface has a "download as PDF" button, but it directs to https://project.lfcla.com/null  which doesn't render. There's a lot of javascript around there, I can't really whats going on. I suspect this is https://github.com/communitybridge/easycla/issues/278

Another issue is that there's no obvious way for users to discover what's going on. I don't see anything a user could click on _before_ opening a PR. I don't see anything in the status messages. Nor do I see it in the EasyCLA interface. Perhaps there's a link, I'd love to know. I suspect this is https://github.com/communitybridge/easycla/issues/265

**Comment by theopolis** [comment]
Is this still an issue?

**Comment by directionless** [comment]
Yes, ish. But I think it's not worth tracking easycla's UX here.
