### ISSUE TITLE
Move osquery downloads

### ISSUE THREAD

**Issue by directionless** [osquery/foundation#45]
The osquery downloads are part of facebook's cloud. We should think about them, and move them. This dovetails with the various CI/CD efforts in osquery

**Comment by caniszczyk** [comment]
how large is the download? you can probably just host it on github's release tool:
https://help.github.com/en/github/administering-a-repository/about-releases

or the new package registry if that's applicable https://github.com/features/packages

**Comment by directionless** [comment]
@theopolis moved this init the osquery AWS account, and I'm looking at fronting that with Fastly.
