### ISSUE TITLE
TSC Transition Ryan to Nick

### ISSUE THREAD

**Issue by directionless** [osquery/foundation#47]
In office hours today, @muffins mentioned that he's been speaking with Ryan (@ryantimwilson) and as Ryan hasn't much been involved with the osquery community, it makes sense to handoff and kind of TSC duties from Ryan to Nick.

For reference,  the [TSC](https://github.com/orgs/osquery/teams/foundation-committers) is currently:
 * seph
 * Zach
 * Ted
 * groob
 * Alessandro
 * Ryan

 I think this raises several questions, which we don't have to formally answer:

1. Can/should we replace Ryan with Nick? 
2. What is our process for replacing TSC members? 
3. What are term lengths for TSC members
4. What are the duties of the TSC members?

**Comment by directionless** [comment]
Speaking as myself, and taking a stab at answering these:

1. I think replacing Ryan with Nick would be a win. Nick has been involved with osquery, he's actively doing work, etc. In contrast I'm not sure I've met Ryan.
2. I think a simple TSC vote is fine? This doesn't feel like it's a substantial change.
3. Someday I'd love to come up with terms and voting processes. But right now, it seems like extra work.
4. I'm not sure. We'e never really formalized it. Somewhat, it's making stuff _go_.

**Comment by alessandrogario** [comment]
1. Nick would be a great addition as a TSC member, providing technical guidance not only as a core developer but also as a Windows expert
2. I think a simple vote is fine; someone will have to notify the Linux foundation about the change (I seem to remember that Teddy notified them about the initial TSC members)
3. I'd like to think members can stay around for as long as they help fulfill the TSC goals
4. I am personally working on things I think osquery should have to stay competitive and be interesting, but I agree that we should formalize this and have more defined goals

**Comment by theopolis** [comment]
Can we also write the name + GitHub handle of the TSC members into the osquery contributing file? This way it is easy to track changes.

**Comment by directionless** [comment]
> Can we also write the name + GitHub handle of the TSC members into the osquery contributing file? This way it is easy to track changes.

Sure, I'll do it when we resolve this ticket. It doesn't change so often it's a burden

**Comment by groob** [comment]
I'm all for the change of adding Nick to the TSC.

As for the other points, I don't think adding limits makes sense for osquery when the size of the project and activity of the community is taken into account. I do think we need to formalize a way of checking in once in a while to see if the folks in this group are still comfortable in the role/can commit to some level of participation.

**Comment by zwass** [comment]
I am on board with this change.

**Comment by directionless** [comment]
Seems like unanimous agreement.

1. I have removed Ryan from https://github.com/orgs/osquery/teams/foundation-committers/members and added Nick. 

Let me know if you want either/both of an invite into the gsuite domain, and an email address to add to the list I use for vendor contacts. (Slack is fine)

I think that's basically it? Other things are sorta just as needed, and end up hitting anyone that seems responsible in the community -- https://github.com/osquery/foundation/blob/master/MOVING_PARTS.md

Feel free to ping me if you have any questions / want to fix anything / etc.

**Comment by directionless** [comment]
I also made https://github.com/osquery/osquery/pull/6253 for teddy's request to stick this in the CONTRIBUTING doc
