### ISSUE TITLE
Transfer osquery-go to the foundation

### ISSUE THREAD

**Issue by directionless** [osquery/foundation#65]
A couple times recently we've talked about transferring https://github.com/kolide/osquery-go from Kolide to the foundation. Having now talked to a handful of people, I believe that this is desired by all parties, and feasible. 

As it stands, the osquery-go project is covered by an MIT license. And it's minimal CLA does notcover re-licensing. Our [charter](https://github.com/osquery/foundation/blob/master/CHARTER.md#7-intellectual-property-policy) requires that all inbound works conform to our usual license. **But** allows the TSC to accept other things on an exception basis. 

This presents us with 3 options:
1. Accept it as it stands. This is obviously simple, but does create some future confusion because it brings in another license to our mix
2. Relicense. This would require contacting all contributors, who were not kolide employees during the time the contributed, and getting signoff to re-license. 
3. Both, do (1) then (2)

I think we should pursue (3). Things that need to happen:
1. TSC needs to signoff on accepting MIT
2. Kolide should sign a thing
3. repo should transfer

I am working on (2) and (3). Can the rest of the TSC (@zwass, @theopolis, @muffins, @groob, @alessandrogario) weigh in? By our charter. electronic voting requires consensus, else majority in a meeting.

**Comment by zwass** [comment]
I will be out the next few days, but please take this as my agreement to transfer the repository under the existing license.

**Comment by directionless** [comment]
We talked about this in office hours today. We had a voice vote of the TSC members present, and we agreed to transfer this in with the current license. We will pursue re-licensing under the foundation.

Present and in favor:
* @directionless 
* @alessandrogario 
* @zwass 
* @theopolis 

No votes against

**Comment by directionless** [comment]
The repo is transferred. Long live https://github.com/osquery/osquery-go

<3 Kolide
