### ISSUE TITLE
1password for opensource

### ISSUE THREAD

**Issue by directionless** [osquery/foundation#7]
We have an 1password team! (thanks @theopolis). 1password will do do free teams for OSS projects. (for the price of named use). Their instructions are at https://github.com/1Password/1password-teams-open-source

I think it's reasonable to add ourselves to that. 👍 / 👎  ? (I'll do that work if we have consensus)

**Comment by theopolis** [comment]
Great idea, thanks for the heads up that this is possible.

https://github.com/1Password/1password-teams-open-source/pull/145
