### ISSUE TITLE
Proposal: Elect Seph as TSC chair

### ISSUE THREAD

**Issue by zwass** [osquery/foundation#81]
@directionless has been contributing to osquery since 2018, and on the Technical Steering Committee since its creation in 2019. He leads most office hours meetings and typically serves as the contact between the TSC and other institutions (Linux Foundation, Apple, etc.)

From the Charter:

> The TSC may elect a TSC Chair, who will preside over meetings of the TSC and will serve until their resignation or replacement by the TSC. The TSC Chair, or any other TSC member so designated by the TSC, will serve as the primary communication contact between the Project and the OSQUERY Fund of The Linux Foundation.

I observe that Seph is essentially performing the above duties, namely presiding over meetings (office hours) and serving as the primary communication contact between osquery and The Linux Foundation.

From the Charter:

> Decisions made by electronic vote without a meeting require a majority vote of all voting members of the TSC.

**I propose that we vote, via this issue, to elect Seph (Joseph Sokol-Margolis) to the position of TSC Chair. All TSC members in favor, please comment in the affirmative.**

If we don't reach a majority of TSC members via electronic voting, I will bring up the matter at the next TSC meeting in which we have a quorum (50% of TSC members).

**Comment by zwass** [comment]
I suppose it's implied by my proposal, but I am in favor 👍

**Comment by alessandrogario** [comment]
@directionless has been working really hard in keeping osquery focused on its core principles, while also bringing a lot of technical knowledge to the table. Ever since osquery was moved under the Linux Foundation, he has been expertly leading many additional efforts including but not limited to community interaction, milestones and release processes, office hours and everything involving legal matters.

I am grateful for all the work and support he has been providing so far, and I am in favor of this proposal!

**Comment by groob** [comment]
I am in favor of this change as well. 👍 👍

**Comment by muffins** [comment]
Yeah, I think @directionless has been crushing it on this front and I think he’d be a great chair, definitely in favor!

**Comment by directionless** [comment]
I would be delighted to accept, but feel like I should abstain from votes about myself.

**Comment by directionless** [comment]
That's 4 yes votes, my abstention, and an absence from Teddy. 

I think this passes.

**Comment by directionless** [comment]
I updated the CONTRIBUTORS in https://github.com/osquery/osquery/pull/7543

**Comment by theopolis** [comment]
Retroactive super 👍 from me :)
