### ISSUE TITLE
Proposal: Elect Sharvil as TSC member

### ISSUE THREAD

**Issue by zwass** [osquery/foundation#82]
@sharvilshah has been contributing to osquery since 2015 and is a go-to expert on macOS development and packaging, along with general osquery development. Notable recent contributions include the development of the new Endpoint Security tables, and support with the M1 port. With his new position at Fleet he will now be focusing full-time on osquery development.

In recognition of Sharvil's efforts, along with a desire to bring more regular contributors into the TSC, I propose electing Sharvil to TSC membership.

From the Charter:

> Decisions made by electronic vote without a meeting require a majority vote of all voting members of the TSC.

**I propose that we vote, via this issue, to elect Sharvil Shah to the position of TSC member. All TSC members in favor, please comment in the affirmative.**

If we don't reach a majority of TSC members via electronic voting, I will bring up the matter at the next TSC meeting in which we have a quorum (50% of TSC members).

**Comment by directionless** [comment]
I am whole heartedly in favor! 👍

**Comment by zwass** [comment]
I suppose it's implied by my proposal, but I am in favor 👍

**Comment by alessandrogario** [comment]
Definitely in favor of this proposal! @sharvilshah has been contributing a lot of technical expertise, and with his experience I think he would be a great addition to the TSC.

**Comment by groob** [comment]
I am in favor too.

**Comment by muffins** [comment]
I am in favor!

**Comment by directionless** [comment]
That's 5 yes votes, every but @theopolis who's been somewhat idle recently.

This passes!

**Comment by zwass** [comment]
Congratulations! 🎉

**Comment by directionless** [comment]
I added @sharvilshah to https://github.com/orgs/osquery/teams/technical-steering-committee/members

and updated CONTRIBUTORS in https://github.com/osquery/osquery/pull/7543

**Comment by theopolis** [comment]
Belated super 👍 from me!
