### ISSUE TITLE
Proposal: Add Marcos Oviedo as an osquery committer

### ISSUE THREAD

**Issue by directionless** [osquery/foundation#86]
@marcosd4h has increasingly been doing more osquery work. He's really stepped up to reviewing Windows related PRs and contributing to the project. I propose we make him a contributor.

I do not believe we have formal policy for this process. I'm going to see if we get approval from a handful of core members, and give folks a chance to raise objections. (If you're not comfortable speaking publicly, feel free to find me on slack or email)

**Comment by sharvilshah** [comment]
This is awesome, 👍 from me!

**Comment by zwass** [comment]
Approved from me. Thank you!

**Comment by alessandrogario** [comment]
Approved from me!

**Comment by Smjert** [comment]
Approved from me too!

**Comment by directionless** [comment]
That's positive comments in this ticket from:
- me
- Sharvil
- Zach
- Alessandro
- Stefano

No negative comments. No one raised private issues. I have added him to committers.
