### ISSUE TITLE
Propose: Add additional maintainers to `osquery-go`

### ISSUE THREAD

**Issue by directionless** [osquery/foundation#87]
Right now, @zwass and I are the only active Go maintainers. This does not feel stable. I propose we add more.

I have created a team [`go-maitainers`](https://github.com/orgs/osquery/teams/go-maintainers/) as ground work, and I'd propose we add:
* @RebeccaMahany -- one of the Kolide go people
* Someone from Fleet, I think Zach mentioned Luke

I'm also open other members of the broader community.

**Comment by zwass** [comment]
@lucasmrod can get involved on the Fleet side.

Happy to have Rebecca joining as well!

**Comment by directionless** [comment]
I think I'm good adding @lucasmrod  and @RebeccaMahany without fill TSC vote. The SDK is you and me, and if we're unanimous here, that seems good enough. I'll give folks a chance to object, then will push buttons.

**Comment by alessandrogario** [comment]
This is a great idea, 👍 from me!

**Comment by sharvilshah** [comment]
👍

**Comment by zwass** [comment]
Seems like we have plenty of buy-in, thanks!

**Comment by directionless** [comment]
I have invited them both. Woo! Welcome

**Comment by lucasmrod** [comment]
Sounds good to me! Looking forward to contributing.
